services:
  archipelago-bot:
    image: {username}/archipelago-bot:latest
    container_name: archipelago-bot
    restart: unless-stopped
    volumes:
      - archipelago_src:/archipelago
    environment:
      - BOT_TOKEN={BOT_TOKEN}
      - SERVER_PASSWORD={SERVER_PASSWORD}

volumes:
  archipelago_src:
